satcoord/coordinations/urls.py
from django.urls import path

from satcoord.coordinations.views import CoordinationDetailView, CoordinationListView, \
    new_coordination_view, review_coordination_view, revise_coordination_view

urlpatterns = [
    path("", CoordinationListView.as_view(), name="coordination-list"),
    path("new/", new_coordination_view, name="coordination-new"),
    path('<int:pk>/', CoordinationDetailView.as_view(), name='coordination-detail'),
    path('<int:coord_id>/review/', review_coordination_view, name='coordination-review'),
    path('<int:coord_id>/revise/', revise_coordination_view, name='coordination-revise'),
]

satcoord/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import include, path

from satcoord.users.views import RegisterView
from satcoord.views import HomeView, SettingsView, get_dashboard_view, robots

urlpatterns = [
    path("admin/", admin.site.urls),
    path("robots.txt", robots, name="robots"),
    path("", HomeView.as_view(), name="home"),
    path("coordinations/", include("satcoord.coordinations.urls")),
    path("accounts/register", RegisterView.as_view(), name="register"),
    path("accounts/login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("overview/", get_dashboard_view, name="overview"),
    path("settings/", SettingsView.as_view(), name="settings")
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

satcoord/coordinations/models.py
"""
The models for the coordination process
"""

from django.conf import settings
from django.db import models, transaction
from django.urls import reverse
from django.utils.timezone import now


class Coordination(models.Model):
    """An application for IARU frequency coordination"""
    UNDER_REVIEW = "r"
    ACCEPTED = "a"
    DECLINED = "d"
    COORD_STATUS_CHOICES = (
        (UNDER_REVIEW, "Under Review"), (ACCEPTED, "Accepted"), (DECLINED, "Declined")
    )

    date = models.DateTimeField(default=now)
    resolvement_date = models.DateTimeField(null=True, blank=True)
    mission_name = models.CharField(unique=True, max_length=50)
    operator_responsible = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL
    )
    supporting_organization = models.CharField(max_length=127)
    description = models.TextField()
    status = models.CharField(max_length=1, choices=COORD_STATUS_CHOICES, default=UNDER_REVIEW)

    def __str__(self):
        return f"Coordination for mission: {self.mission_name} - {self.get_status_display()}"

    def __review_coord(self, comments, new_status=None):
        """Helper method for setting status"""
        latest_rev = self.get_latest_revision()
        with transaction.atomic():
            if new_status:
                self.status = new_status
                self.resolvement_date = now()
                self.save()
            latest_rev.is_addressed = True
            latest_rev.comments = comments
            latest_rev.save()

    def accept(self, comments=""):
        """Mark coordination as accepted"""
        self.__review_coord(comments, new_status=self.ACCEPTED)

    def decline(self, comments=""):
        """Mark coordination as declined"""
        self.__review_coord(comments, new_status=self.DECLINED)

    def needs_changes(self, comments):
        """Adds comments to latest revision"""
        self.__review_coord(comments)

    def is_owner(self, user):
        """Return True if user is the one who issued the coordination application"""
        return not user.is_anonymous and user.id == self.operator_responsible_id

    def can_view_revisions(self, user):
        """Return True if user is allowed to view revisions"""
        return bool(self.is_owner(user) or user.has_perm("view_revisions"))

    def get_absolute_url(self):
        """Returns the absolute url for the instance detail view"""
        return reverse("coordination-detail", kwargs={"pk": self.pk})

    def get_latest_revision(self):
        """Returns the latest revision of this coordination"""
        try:
            return self.revisions.latest("id")
        except Revision.DoesNotExist:
            return None

    def is_reviewable(self):
        """Returns whether a panel member can review the coordination"""
        if self.status == Coordination.UNDER_REVIEW:
            latest_rev = self.get_latest_revision()
            if latest_rev and not latest_rev.is_addressed:
                return True
        return False

    def is_revisable(self):
        """Returns whether the applicant can provide revisions for the coordination"""
        if self.status == Coordination.UNDER_REVIEW:
            latest_rev = self.get_latest_revision()
            if latest_rev and latest_rev.is_addressed:
                return True
        return False

    def can_user_revise(self, user):
        """Returns whether user can provide revisions for the coordination"""
        return self.is_owner(user) and self.is_revisable()

    def get_detailed_status_display(self):
        """Returns a detailed status"""
        if self.status == Coordination.UNDER_REVIEW:
            latest_rev = self.get_latest_revision()
            if latest_rev and latest_rev.is_addressed:
                return "Needs Changes"
        return self.get_status_display()

    class Meta:
        permissions = [
            ("view_revisions", "Can view the coordination's revisions"),
            ("review_coordinations", "Can review a coordination"),
        ]


class Beam(models.Model):
    """A beam that corresponds to a Coordination"""
    E2S = "e2s"
    S2E = "s2e"
    S2S = "s2s"
    DIRECTION_CHOICES = ((E2S, "Earth to space"), (S2E, "Space to earth"), (S2S, "Space to space"))
    MODES = (
        "AFSK",
        "AFSK S-Net",
        "AFSK SALSAT",
        "AHRPT",
        "AM",
        "APT",
        "BPSK",
        "BPSK PMT-A3",
        "CERTO",
        "CW",
        "DQPSK",
        "DSTAR",
        "DUV",
        "FFSK",
        "FM",
        "FMN",
        "FSK",
        "FSK AX.100 Mode 5",
        "FSK AX.100 Mode 6",
        "FSK AX.25 G3RUH",
        "GFSK",
        "GFSK Rktr",
        "GFSK/BPSK",
        "GMSK",
        "HRPT",
        "LRPT",
        "LSB",
        "MFSK",
        "MSK",
        "MSK AX.100 Mode 5",
        "MSK AX.100 Mode 6",
        "OFDM",
        "OQPSK",
        "PSK",
        "PSK31",
        "PSK63",
        "QPSK",
        "QPSK31",
        "QPSK63",
        "SSTV",
        "USB",
        "WSJT",
    )

    BANDS = ("HF", "UHF", "VHF", "SHF", "EHF")

    coordination = models.ForeignKey(Coordination, related_name="beams", on_delete=models.CASCADE)
    direction = models.CharField(max_length=3, choices=DIRECTION_CHOICES)
    band = models.CharField(max_length=127, choices=zip(BANDS, BANDS))
    modulation = models.CharField(max_length=127, choices=zip(MODES, MODES))
    description = models.TextField(blank=True)
    service_area = models.CharField(max_length=128)

    def __str__(self):
        return f"{self.get_direction_display()} beam for {self.coordination}"


class Revision(models.Model):
    """A revision of a coordinatiion"""
    file = models.FileField(upload_to='revisions/%Y/%m/%d/')
    comments = models.TextField(blank=True)
    coordination = models.ForeignKey(
        Coordination, on_delete=models.CASCADE, related_name="revisions"
    )
    date = models.DateTimeField(default=now)
    revision_number = models.PositiveSmallIntegerField()
    is_addressed = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.revision_number = Revision.objects.filter(coordination_id=self.coordination_id
                                                           ).count() + 1
        super().save()

    def get_coordination_url(self):
        """Returns the url of the coordination"""
        return self.coordination.get_absolute_url()

    def __str__(self):
        return f"Revision #{self.revision_number} for {self.coordination}"

satcoord/coordinations/forms.py
from django import forms
from django.core.exceptions import ValidationError

from satcoord.coordinations.models import Beam, Coordination, Revision


class BootstrapFormMixin:  # pylint: disable=R0903
    """Mixin to add classes and 'required' to form fields"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
            if hasattr(visible, "field") and visible.field.required:
                visible.field.widget.attrs["required"] = "required"


class CoordinationForm(BootstrapFormMixin, forms.ModelForm):
    """Form for creating a new Coordination application"""
    template_name = "coordinations/forms/new_coordination_form.html"

    class Meta:
        model = Coordination
        fields = ["mission_name", "supporting_organization", "description"]


class BeamForm(BootstrapFormMixin, forms.ModelForm):
    """Form for adding a Beam to a Coordination"""

    class Meta:
        model = Beam
        fields = [
            "direction",
            "modulation",
            "band",
            "service_area",
            "description",
        ]


class RevisionForm(forms.ModelForm):
    """Form for adding a Revision to a Coordination"""

    class Meta:
        model = Revision
        fields = ["file"]


class ReviewForm(BootstrapFormMixin, forms.Form):
    """Form for reviewing coordinations"""

    NEEDS_CHANGES = "c"
    ACCEPTED = "a"
    DECLINED = "d"
    REVIEW_STATUS_CHOICES = (
        (ACCEPTED, "Accepted"), (DECLINED, "Declined"), (NEEDS_CHANGES, "Needs Changes")
    )

    verdict = forms.ChoiceField(choices=REVIEW_STATUS_CHOICES)
    comments = forms.CharField(
        required=False, widget=forms.Textarea(attrs={
            "rows": 4,
            "style": "height:9rem"
        })
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial["verdict"] = self.NEEDS_CHANGES

    def clean(self):
        cleaned_data = super().clean()
        verdict = cleaned_data.get("verdict")
        comments = cleaned_data.get("comments")

        if verdict == self.NEEDS_CHANGES and not comments:
            raise ValidationError(
                "If the coordination application needs changes, \
the reviewer must provide relevant comments."
            )


class BeamDeleteForm(forms.Form):
    """A form for deleting beams of a coordination"""
    beams_to_delete = forms.ModelMultipleChoiceField(queryset=Beam.objects.none(), required=False)

    def __init__(self, *args, **kwargs):
        queryset = kwargs.pop("queryset")
        super().__init__(*args, **kwargs)
        self.fields["beams_to_delete"].queryset = queryset

satcoord/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import EmailField


class RadioAmateurCreationForm(UserCreationForm):
    """
    A form that creates a user, with no privileges.
    """

    template_name = "registration/forms/register.html"
    auto_id = "register_%s"

    def __init__(self, *args, **kwargs):
        if not kwargs.get("auto_id"):
            kwargs["auto_id"] = self.auto_id
        super().__init__(*args, **kwargs)

    class Meta:
        model = get_user_model()
        fields = ("callsign", "email", "first_name", "last_name")
        field_classes = {"email": EmailField}

satcoord/users/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from satcoord.users.forms import RadioAmateurCreationForm


class RegisterView(generic.CreateView):
    """View for registering new users"""
    form_class = RadioAmateurCreationForm
    success_url = reverse_lazy("home")
    template_name = "registration/register.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.success_url)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """
        Creates a new user and logs them in.
        """
        form = self.get_form()
        self.object = None  # pylint: disable=attribute-defined-outside-init
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(
                callsign=form.cleaned_data['callsign'],
                password=form.cleaned_data['password1'],
            )
            login(request, new_user)
            return HttpResponseRedirect(self.success_url)
        return self.form_invalid(form)

satcoord/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView

from satcoord.coordinations.models import Coordination, Revision


def robots(request):
    """Returns response for robots.txt requests"""
    data = render(request, "robots.txt", {"environment": settings.ENVIRONMENT})
    response = HttpResponse(data, content_type="text/plain; charset=utf-8")
    return response


class SettingsView(LoginRequiredMixin, TemplateView):
    """View responsible for rendering settings page"""
    template_name = "settings.html"


class HomeView(TemplateView):
    """View responsible for rendering home page"""
    template_name = "home.html"


class PanelMemberDashboardView(TemplateView):
    """View for displaying an overview for Panel Members"""

    template_name = "dashboard/panel_member_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        unaddressed_revisions = Revision.objects.filter(
            is_addressed=False
        ).select_related("coordination").order_by("-id")
        unaddressed_coords = []
        new_coords = []
        for rev in unaddressed_revisions:
            coord = rev.coordination
            coord.latest_revision = rev
            if rev.revision_number == 1:
                new_coords.append(coord)
            else:
                unaddressed_coords.append(coord)

        context["new_coords"] = new_coords
        context["has_new_coords"] = bool(new_coords)
        context["unaddressed_coords"] = unaddressed_coords
        context["has_unaddressed_coords"] = bool(unaddressed_coords)

        return context


class UserDashboardView(TemplateView):
    """View for displaying an overview for RadioAmateurs"""

    template_name = "dashboard/user_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        coords = Coordination.objects.filter(operator_responsible_id=self.request.user.id
                                             ).prefetch_related("revisions")
        need_change = []
        pending_review = []
        accepted = []
        declined = []
        for coord in coords:
            if coord.status == Coordination.UNDER_REVIEW:
                if coord.get_latest_revision().is_addressed:
                    need_change.append(coord)
                else:
                    pending_review.append(coord)
            elif coord.status == Coordination.ACCEPTED:
                accepted.append(coord)
            else:
                declined.append(coord)
        context["coords"] = coords
        context["need_change"] = need_change
        context["pending_review"] = pending_review
        context["accepted"] = accepted
        context["declined"] = declined
        context["has_coords"] = bool(coords)
        context["has_need_change"] = bool(need_change)
        context["has_pending_review"] = bool(pending_review)
        context["has_accepted"] = bool(accepted)
        context["has_declined"] = bool(declined)

        return context


@login_required
def get_dashboard_view(request, *args, **kwargs):
    """Selects appropriate dashboard view"""
    if request.user.groups.filter(name="Panel Members").exists():
        return PanelMemberDashboardView.as_view()(request, *args, **kwargs)
    return UserDashboardView.as_view()(request, *args, **kwargs)

satcoord/templates/coordinations/coordinations_detail.html
{% extends "base.html" %}
{% load static %}
{% load utility_filters %}
{% block title %}
  - {{ coordination.mission_name }}
{% endblock title %}
{% block content %}
  <div class="container px-md-5 py-5 my-5 card">
    <a class="d-flex align-items-center mb-5 text-decoration-on-hover w-fit-content"
       href="{{ back_url }}">
      <i class="me-3">
        <svg xmlns="http://www.w3.org/2000/svg"
             width="25"
             height="25"
             fill="currentColor"
             class="bi bi-arrow-left-circle"
             viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
        </svg>
      </i>
      Back to list
    </a>
    {% if show_review_tools %}
      <div class="collapse mb-3 {% if review_form_open %}show{% endif %}"
           id="review-container">
        {% include "./includes/coordinations_review.html" with form=review_form coord=coordination %}
      </div>
    {% endif %}
    <h1 class="mb-4">
      {{ coordination.mission_name }}
      <br />
      <span class="fs-6 align-middle badge badge-color-for-status-{{ coordination.status }} fw-normal">
        {% if show_revisions %}
          {{ coordination.get_detailed_status_display }}
        {% else %}
          {{ coordination.get_status_display }}
        {% endif %}
      </span>
      {% if show_review_tools or show_revise_tools %}
        <i>
          <svg xmlns="http://www.w3.org/2000/svg"
               width="16"
               height="16"
               fill="currentColor"
               class="bi bi-arrow-bar-left"
               viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5ZM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5Z"/>
          </svg>
        </i>
      {% endif %}
      {% if show_review_tools %}
        <button type="button"
                data-bs-toggle="collapse"
                data-bs-target="#review-container"
                aria-expanded="{{ review_form_open|js_bool }}"
                aria-controls="review-container"
                class="btn btn-outline-dark">
          <i class="me-2">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="20"
                 height="20"
                 fill="currentColor"
                 class="bi bi-card-checklist"
                 viewBox="0 0 16 16">
              <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
              <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z"/>
            </svg>
          </i>Review Coordination
        </button>
      {% elif show_revise_tools %}
        <a href="{% url 'coordination-revise' coord_id=coordination.id %}"
           class="btn btn-outline-dark">
          <i class="me-2">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="20"
                 height="20"
                 fill="currentColor"
                 class="bi bi-pencil-square"
                 viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
          </i>Revise Coordination
        </a>
      {% endif %}
    </h1>
    <div class="container-fluid">
      <div class="row flex-row-reverse mb-5">
        <div class="ps-lg-3 p-0 col-12 col-lg-6">
          <table class="ms-n2 m-lg-0 table table-borderless">
            <tr>
              <th class="pt-0" scope="row">
                <span>Supporting Organization:</span>
              </th>
              <td class="pt-0">
                <span>{{ coordination.supporting_organization }}</span>
              </td>
            </tr>
            <tr>
              <th scope="row">
                <span>Date of Application:</span>
              </th>
              <td>
                <span>{{ coordination.date|date:"M d, Y" }}</span>
              </td>
            </tr>
            <tr>
              <th scope="row">
                <span>Operator Responsible:</span>
              </th>
              <td>
                <span>{{ coordination.operator_responsible.get_full_name }} - {{ coordination.operator_responsible.callsign }}</span>
              </td>
            </tr>
          </table>
        </div>
        <div class="pe-lg-3 p-0 col-12 col-lg-6">
          <div id="coord-description-div">
            <p class="collapse mb-1" id="coord-description">{{ coordination.description }}</p>
            <div id="expander-container" class="d-none">
              <a class="collapsed"
                 data-bs-toggle="collapse"
                 href="#coord-description"
                 aria-expanded="false"
                 aria-controls="coord-description"></a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="pe-lg-3 p-0 col-12 col-lg-6">
          {% if show_revisions %}
            <div class="accordion" id="revisions">
              <h2 class="mb-3 h3">Revisions</h2>
              <div class="d-flex flex-column-reverse">
                {% for rev in coordination.revisions.all %}
                  <div class="accordion-item">
                    <h3 class="accordion-header" id="revision-heading-{{ rev.id }}">
                      <button class="accordion-button"
                              type="button"
                              data-bs-toggle="collapse"
                              data-bs-target="#revision-collapse-{{ rev.id }}"
                              aria-expanded="false"
                              aria-controls="revision-collapse-{{ rev.id }}">
                        Revision #{{ rev.revision_number }} - {{ rev.date }}
                      </button>
                    </h3>
                    <div id="revision-collapse-{{ rev.id }}"
                         class="accordion-collapse collapse"
                         aria-labelledby="revision-heading-{{ rev.id }}"
                         data-bs-parent="#revisions">
                      <div class="accordion-body">
                        <div class="mb-3">
                          <a href="{{ rev.file.url }}">Download file
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 width="16"
                                 height="16"
                                 fill="currentColor"
                                 class="bi bi-download ms-2 pb-1"
                                 viewBox="0 0 16 16">
                              <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                              <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                            </svg>
                          </a>
                        </div>
                        {% if rev.comments %}
                          <div>
                            <strong>Comments:
                              <br/>
                            </strong>
                            {{ rev.comments }}
                          </div>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                {% empty %}
                  No revisions to display
                {% endfor %}
              </div>
            </div>
          {% endif %}
        </div>
        <div class="ps-lg-3 p-0 col-12 col-lg-6">
          <div class="accordion" id="beams">
            <h2 class="mb-3 h3">Beams</h2>
            {% for beam in coordination.beams.all %}
              <div class="accordion-item">
                <h3 class="accordion-header" id="beam-heading-{{ beam.id }}">
                  <button class="accordion-button"
                          type="button"
                          data-bs-toggle="collapse"
                          data-bs-target="#beam-collapse-{{ beam.id }}"
                          aria-expanded="false"
                          aria-controls="beam-collapse-{{ beam.id }}">
                    {{ beam.get_direction_display }} - {{ beam.get_modulation_display }} - {{ beam.get_band_display }}
                  </button>
                </h3>
                <div id="beam-collapse-{{ beam.id }}"
                     class="accordion-collapse collapse"
                     aria-labelledby="beam-heading-{{ beam.id }}"
                     data-bs-parent="#beams">
                  <div class="accordion-body">
                    <table class="table table-borderless mx-n2">
                      <tr>
                        <th scope="row">
                          <span>Direction:</span>
                        </th>
                        <td>
                          <span>{{ beam.get_direction_display }}</span>
                        </td>
                      </tr>
                      <tr>
                        <th scope="row">
                          <span>Modulation:</span>
                        </th>
                        <td>
                          <span>{{ beam.get_modulation_display }}</span>
                        </td>
                      </tr>
                      <tr>
                        <th scope="row">
                          <span>Band:</span>
                        </th>
                        <td>
                          <span>{{ beam.get_band_display }}</span>
                        </td>
                      </tr>
                      <tr>
                        <th scope="row">
                          <span>Service Area:</span>
                        </th>
                        <td>
                          <span>{{ beam.service_area }}</span>
                        </td>
                      </tr>
                    </table>
                    {{ beam.description }}
                  </div>
                </div>
              </div>
            {% empty %}
              <span>No beams for this coordination</span>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block javascript %}
  <script src="{% static 'js/coord-detail-description.js'%}"></script>
{% endblock javascript %}

satcoord/templates/coordinations/coordinations_new.html
{% extends "coordinations/coordinations_form_base.html" %}
{% block title %}
  - New Coordination
{% endblock title %}
{% block form_header %}
  New Coordination
{% endblock form_header %}
{% block form_action %}
  action="{% url 'coordination-new' %}"
{% endblock form_action %}
{% block beams %}
  <div id="beam-forms-container" class="d-flex flex-column-reverse">
    {% for form in beam_formset %}
      {% include "./forms/beam_form.html" with form=form loop_idx=forloop.counter0 %}
    {% endfor %}
    {% if beam_formset.non_field_errors %}
      <div class="alert alert-danger form-errors" role="alert">{{ beam_formset.non_field_errors }}</div>
    {% endif %}
  </div>
{% endblock beams %}